config/routes.rb
Rails.application.routes.draw do
  root to: "questions#index"

  devise_for :users

  resources :questions do
    resources :answers, only: [:new, :create]
  end

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  belongs_to :user

  validates :title, :body ,presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :questions, dependent: :destroy

  def author?(entity)
    id == entity.user_id
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  before_action :load_question, only: [:create]

  def create
    @answer = @question.answers.new(answer_params)

    if @answer.save
      redirect_to @question, notice: 'Your answer successfully created.'
    else
      flash[:alert] = 'Not correct answer data'
      render 'questions/show'
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def load_question
    @question = Question.find(params[:question_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :load_question, only: [ :show, :edit, :update, :destroy ]
  before_action :authenticate_user!, except: [ :index, :show ]

  def index
    @questions = Question.all
  end

  def show
  end

  def new
    @question = Question.new
  end

  def edit
  end

  def create
    @question = current_user.questions.new(question_params)
    if @question.save
      redirect_to @question, notice: 'Your question successfully created.'
    else
      flash[:alert] = 'Not the correct question data!'
    end
  end

  def update
    if @question.update(question_params)
      redirect_to @question
    else
      render :edit
    end
  end

  def destroy
    if current_user.author?(@question)
      @question.destroy
      redirect_to question_path, notice: 'Question was successfully deleted'
    else
      redirect_to @question
      flash[:alert] = 'Something wrong, try to delete your own question'
    end
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_form.html.slim
= form_for [question, question.answers.build] do |f|
  = f.label :body
  br
  = f.text_area :body
  br
  = f.submit 'Add new answer'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qna</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to('Main page', root_path) %>
    <div>
      <ul>
      <% if user_signed_in? %>
        <li>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
        </li>
      <% else %>
        <li>
          <%= link_to('Login', new_user_session_path)  %>
        </li>
        <li>
          <%= link_to('Sign up', new_user_registration_path)  %>
        </li>
      <% end %>
      </ul>
    </div>
    <p class='notice'><%= notice %></p>
    <p class='alert'><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Qna
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    div
      ul
        - if user_signed_in?
          li
            = link_to('Logout', destroy_user_session_path, :method => :delete)
        - else
          li
            = link_to('Login', new_user_session_path)
          li
            = link_to('Sign up', new_user_registration_path)
    p.notice= notice
    p.alert= alert
    = yield

doctype html
  html
    head
      title
        | Qna
      = csrf_meta_tags
      = csp_meta_tag
      = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
      = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    body
      div
        ul
          - if user_signed_in?
            li
              = link_to('Logout', destroy_user_session_path, :method => :delete)
          - else
            li
              = link_to('Login', new_user_session_path)
            li
              = link_to('Sign up', new_user_registration_path)
      p.notice
        = notice
      p.alert
        = alert
      = yield

app/views/questions/index.html.slim
- @questions.each do |question|
  h4.title.is-4
    = link_to question.title, question


p= link_to 'Ask question', new_question_path

/ h2
/   | List questions
/ - @questions.each do |question|
/     h3
/       = link_to question.title, question_path(question)

app/views/questions/new.html.slim
= form_for @question do |f|
  = f.label :title
  = f.text_field :title
  br
  br
  = f.label :body
  = f.text_area :body
  br
  = f.submit 'Create'

app/views/questions/show.html.slim
h2 = @question.title
div = @question.body

- if user_signed_in? && current_user.author?(@question)
    div
      = link_to 'Delete question', @question, method: :delete

- if @question.answers.any?
    div class="answers"
      - @question.answers.each do |answer|
        div class="answer" = answer.body

div class="form_add_answer"
  = render 'answers/form', question: @question